# Generated by Django 3.0.6 on 2020-05-15 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_auto_20200515_1605'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Airport',
        ),
    ]
